/* ============================================================
   英雄圍城 物價表 —— 改這裡，存檔，重新整理網頁就生效。

   遊戲：Hero Siege（Steam 269210），第十季 Ebontharn。
   道具名單整理自 herosiegedata.com，共 228 筆。

   ── 怎麼記價格 ───────────────────────────────
   找到那一行，把 price 的引號裡填上數字：

       { g:"詞綴工藝材料", name:"撒旦骰子", ... price:"", ... }
                                                    ↓
       { g:"詞綴工藝材料", name:"撒旦骰子", ... price:"1200", ... }

   留空白 = 還沒記，網頁顯示「未記錄」。
   "2.5k"、"約 80"、"2~3" 都可以，網頁原樣顯示；
   只有純數字的才會參與價格排序。

   ── 欄位 ─────────────────────────────────────
   g      分類          name  中文名        en    英文名
   price  價格          lv    等級需求      note  備註
   icon   圖檔名（選填，圖片放 img/hs/，副檔名不用寫）
   ============================================================ */

/* 計價單位。改這裡，整頁的單位跟著變。 */
const HS_UNIT = "金幣";

/* 分類的顯示順序。沒列到的排最後面。 */
const HS_GROUPS = ["詞綴工藝材料", "礦石", "寶石", "靈魂寶石與寶球", "塔羅牌", "碎片與王材料", "鑰匙", "地下城鑰匙", "特殊消耗品"];

const HS_ITEMS = [

  /* ═══ 詞綴工藝材料 ═══ */
  { g:"詞綴工藝材料", name:"撒旦水晶",           en:"Satanic Crystal",              price:"", note:"加一條隨機詞綴或孔洞，失敗則腐化", },
  { g:"詞綴工藝材料", name:"撒旦水晶碎片",       en:"Satanic Crystal Fragment",     price:"", note:"500 個合一顆撒旦水晶", },
  { g:"詞綴工藝材料", name:"撒旦骰子",           en:"Satanic Dice",                 price:"", note:"重骰裝備數值，有機率腐化。20 碎片合一顆", },
  { g:"詞綴工藝材料", name:"撒旦骰子碎片",       en:"Dice Fragment",                price:"", note:"20 個合一顆撒旦骰子", },
  { g:"詞綴工藝材料", name:"祝福骰子",           en:"Blessed Dice",                 price:"", note:"SS 階專用重骰，無副作用", },
  { g:"詞綴工藝材料", name:"修補匠的工具包",     en:"Tinkerer's Toolkit",           price:"", note:"重骰一般物品的全部詞綴", },
  { g:"詞綴工藝材料", name:"命運碎片",           en:"Destiny Shard",                price:"", note:"S 階以下升降階，可能腐化", },
  { g:"詞綴工藝材料", name:"命運碎片殘片",       en:"Destiny Shard Fragment",       price:"", note:"合成命運碎片", },
  { g:"詞綴工藝材料", name:"吉普賽的預言",       en:"Gypsy's Prophecy",             price:"", note:"SS 階升降階，可能腐化。20 碎片合一個", },
  { g:"詞綴工藝材料", name:"吉普賽預言碎片",     en:"Gypsy's Fragment",             price:"", note:"20 個合一份吉普賽的預言", },
  { g:"詞綴工藝材料", name:"少量撒旦之塵(D)",    en:"Minor Satanic Dust",           price:"", note:"升 D 階惡魔裝星級", },
  { g:"詞綴工藝材料", name:"次級撒旦之塵(C)",    en:"Lesser Satanic Dust",          price:"", note:"升 C 階惡魔裝星級", },
  { g:"詞綴工藝材料", name:"撒旦之塵(B)",        en:"Satanic Dust",                 price:"", note:"升 B 階惡魔裝星級", },
  { g:"詞綴工藝材料", name:"豐富撒旦之塵(A)",    en:"Rich Satanic Dust",            price:"", note:"升 A 階惡魔裝星級", },
  { g:"詞綴工藝材料", name:"強化撒旦之塵(S)",    en:"Empowered Satanic Dust",       price:"", note:"升 S 階惡魔裝星級", },
  { g:"詞綴工藝材料", name:"純淨撒旦之塵(SS)",   en:"Purified Satanic Dust",        price:"", note:"升 SS 階惡魔裝星級", },
  { g:"詞綴工藝材料", name:"少量神話之塵",       en:"Minor Mythic Dust",            price:"", note:"升 D 階普通裝星級", },
  { g:"詞綴工藝材料", name:"次級神話之塵",       en:"Lesser Mythic Dust",           price:"", note:"升 C 階普通裝星級", },
  { g:"詞綴工藝材料", name:"神話之塵",           en:"Mythic Dust",                  price:"", note:"升 B 階普通裝星級", },
  { g:"詞綴工藝材料", name:"強化神話之塵",       en:"Empowered Mythic Dust",        price:"", note:"升 A 階普通裝星級", },
  { g:"詞綴工藝材料", name:"豐富的神話之塵",     en:"Rich Mythic Dust",             price:"", note:"升 S 階普通裝星級", },
  { g:"詞綴工藝材料", name:"天使之塵",           en:"Angelic Dust",                 price:"", note:"升天使／邪惡裝星級", },
  { g:"詞綴工藝材料", name:"先知的智慧",         en:"Prophet's Wisdom",             price:"", note:"洗回英雄級以下的腐化裝", },
  { g:"詞綴工藝材料", name:"天使的智慧",         en:"Angel's Wisdom",               price:"", note:"洗回天使／邪惡裝的腐化", },
  { g:"詞綴工藝材料", name:"塔雷希爾的倒影",     en:"Reflection of Tarethiel",      price:"", note:"複製一件裝備，複製品不能再複製", },
  { g:"詞綴工藝材料", name:"鐵匠之槌",           en:"Blacksmith's Mallet",          price:"", note:"拆掉一般物品的所有鑲孔。20 碎片合一把", },
  { g:"詞綴工藝材料", name:"鐵匠之槌碎片",       en:"Mallet Fragment",              price:"", note:"20 個合一把鐵匠之槌", },
  { g:"詞綴工藝材料", name:"法典頁面",           en:"Codex Page",                   price:"", note:"5 張合一本永恆法典", },
  { g:"詞綴工藝材料", name:"永恆法典",           en:"Eternity Codex",               price:"", note:"把區域變成惡魔區域", },
  { g:"詞綴工藝材料", name:"煉獄法典書頁",       en:"Infernal Codex Page",          price:"", note:"5 張合一本煉獄法典", },
  { g:"詞綴工藝材料", name:"煉獄法典",           en:"Infernal Codex",               price:"", note:"永恆法典的煉獄版", },
  { g:"詞綴工藝材料", name:"混沌精華",           en:"Essence of Chaos",             price:"", note:"注入煉獄法典，多一組增益與減益", },
  { g:"詞綴工藝材料", name:"神授法師徽記",       en:"God Empowered Mage Emblem",    price:"", note:"武器神聖附魔（法術）", },
  { g:"詞綴工藝材料", name:"神授戰士徽記",       en:"God Empowered Warrior Emblem", price:"", note:"武器神聖附魔（戰鬥）", },
  { g:"詞綴工藝材料", name:"神授遊俠徽記",       en:"God Empowered Ranger Emblem",  price:"", note:"武器神聖附魔（遠程）", },
  { g:"詞綴工藝材料", name:"惡魔授予的徽記",     en:"Devil Empowered Emblem",       price:"", note:"平衡神聖附魔，讓它更強", },
  { g:"詞綴工藝材料", name:"魔法符印",           en:"Enchanted Sigil",              price:"", note:"永恆死亡護符要 2 個", },
  { g:"詞綴工藝材料", name:"較小的不穩定粉塵",   en:"Lesser Unstable Dust",         price:"", note:"合成隨機碎片", },
  { g:"詞綴工藝材料", name:"不穩定粉塵",         en:"Unstable Dust",                price:"", note:"合成隨機碎片", },
  { g:"詞綴工藝材料", name:"更大的不穩定粉塵",   en:"Greater Unstable Dust",        price:"", note:"合成隨機碎片", },
  { g:"詞綴工藝材料", name:"阿托的老鼠",         en:"Ahto's Rat",                   price:"", note:"綿羊之地三材料之一", },
  { g:"詞綴工藝材料", name:"尤西的水煙壺",       en:"Jussi's Bong",                 price:"", note:"綿羊之地三材料之一", },
  { g:"詞綴工藝材料", name:"羊皮",               en:"Sheep Pelt",                   price:"", note:"綿羊之地三材料之一", },
  { g:"詞綴工藝材料", name:"可食用PAS標誌",      en:"Edible PAS Logo",              price:"", note:"三材料合成，使用後進綿羊之地", },

  /* ═══ 礦石 ═══ */
  { g:"礦石", name:"銅礦石",             en:"Copper Ore",                   price:"", note:"探勘出：血石、蛇牙、銅石、液化石", },
  { g:"礦石", name:"鐵礦石",             en:"Iron Ore",                     price:"", note:"探勘出：黑石、小惡魔石、鐵蛋白石、暗影石", },
  { g:"礦石", name:"黃金礦石",           en:"Gold Ore",                     price:"", note:"探勘出：暮光黃水晶、海洋瑪瑙、大惡魔石、巨大錳鎂石榴石", },
  { g:"礦石", name:"紅寶石礦石",         en:"Ruby Ore",                     price:"", note:"探勘出：鮮紅紅寶石、火焰核心、惡魔之牙、卡塔礦石", },
  { g:"礦石", name:"玉礦石",             en:"Jade Ore",                     price:"", note:"探勘出：玉石粉、撒旦指甲、煉獄石、地獄之星", },
  { g:"礦石", name:"塔雷希爾礦石",       en:"Tarethiel Ore",                price:"", note:"探勘出：塔雷希爾核心、暗物質、惡魔靈魂石、暴風蛋白石", },

  /* ═══ 寶石 ═══ */
  { g:"寶石", name:"碎裂紅寶石",         en:"Chipped_Ruby",                 price:"", lv:"1", note:"+8 附加火焰傷害、+4 基礎火焰技能傷害", icon:"Chipped_Ruby_spr_0", },
  { g:"寶石", name:"瑕疵紅寶石",         en:"Flawed_Ruby",                  price:"", lv:"5", note:"+24 附加火焰傷害、+7 基礎火焰技能傷害", icon:"Flawed_Ruby_spr_0", },
  { g:"寶石", name:"紅寶石",             en:"Ruby",                         price:"", lv:"12", note:"+48 附加火焰傷害、+10 基礎火焰技能傷害", icon:"Ruby_spr_0", },
  { g:"寶石", name:"無暇紅寶石",         en:"Flawless_Ruby",                price:"", lv:"15", note:"+128 附加火焰傷害、+13 基礎火焰技能傷害", icon:"Flawless_Ruby_spr_0", },
  { g:"寶石", name:"完美紅寶石",         en:"Perfect_Ruby",                 price:"", lv:"24", note:"+256 附加火焰傷害、+16 基礎火焰技能傷害", icon:"Perfect_Ruby_spr_0", },
  { g:"寶石", name:"嶄新紅寶石",         en:"Pristine_Ruby",                price:"", lv:"38", note:"+512 附加火焰傷害、+20 基礎火焰技能傷害", icon:"Pristine_Ruby_spr_0", },
  { g:"寶石", name:"碎裂藍寶石",         en:"Chipped_Sapphire",             price:"", lv:"1", note:"+8 附加冰霜傷害、+4 基礎冰霜技能傷害", icon:"Chipped_Sapphire_spr_0", },
  { g:"寶石", name:"瑕疵藍寶石",         en:"Flawed_Sapphire",              price:"", lv:"5", note:"+24 附加冰霜傷害、+7 基礎冰霜技能傷害", icon:"Flawed_Sapphire_spr_0", },
  { g:"寶石", name:"藍寶石",             en:"Sapphire",                     price:"", lv:"12", note:"+48 附加冰霜傷害、+10 基礎冰霜技能傷害", icon:"Sapphire_spr_0", },
  { g:"寶石", name:"無暇藍寶石",         en:"Flawless_Sapphire",            price:"", lv:"15", note:"+128 附加冰霜傷害、+13 基礎冰霜技能傷害", icon:"Flawless_Sapphire_spr_0", },
  { g:"寶石", name:"完美藍寶石",         en:"Perfect_Sapphire",             price:"", lv:"24", note:"+256 附加冰霜傷害、+16 基礎冰霜技能傷害", icon:"Perfect_Sapphire_spr_0", },
  { g:"寶石", name:"嶄新藍寶石",         en:"Pristine_Sapphire",            price:"", lv:"38", note:"+512 附加冰霜傷害、+20 基礎冰霜技能傷害", icon:"Pristine_Sapphire_spr_0", },
  { g:"寶石", name:"碎裂綠寶石",         en:"Chipped_Emerald",              price:"", lv:"1", note:"+8 附加毒素傷害、+4 基礎毒素技能傷害", icon:"Chipped_Emerald_spr_0", },
  { g:"寶石", name:"瑕疵綠寶石",         en:"Flawed_Emerald",               price:"", lv:"5", note:"+24 附加毒素傷害、+7 基礎毒素技能傷害", icon:"Flawed_Emerald_spr_0", },
  { g:"寶石", name:"綠寶石",             en:"Emerald",                      price:"", lv:"12", note:"+48 附加毒素傷害、+10 基礎毒素技能傷害", icon:"Emerald_spr_0", },
  { g:"寶石", name:"無暇綠寶石",         en:"Flawless_Emerald",             price:"", lv:"15", note:"+128 附加毒素傷害、+13 基礎毒素技能傷害", icon:"Flawless_Emerald_spr_0", },
  { g:"寶石", name:"完美綠寶石",         en:"Perfect_Emerald",              price:"", lv:"24", note:"+256 附加毒素傷害、+16 基礎毒素技能傷害", icon:"Perfect_Emerald_spr_0", },
  { g:"寶石", name:"嶄新綠寶石",         en:"Pristine_Emerald",             price:"", lv:"38", note:"+512 附加毒素傷害、+20 基礎毒素技能傷害", icon:"Pristine_Emerald_spr_0", },
  { g:"寶石", name:"碎裂黃寶石",         en:"Chipped_Topaz",                price:"", lv:"1", note:"+8 附加閃電傷害、+4 基礎閃電技能傷害", icon:"Chipped_Topaz_spr_0", },
  { g:"寶石", name:"瑕疵黃寶石",         en:"Flawed_Topaz",                 price:"", lv:"5", note:"+24 附加閃電傷害、+7 基礎閃電技能傷害", icon:"Flawed_Topaz_spr_0", },
  { g:"寶石", name:"黃寶石",             en:"Topaz",                        price:"", lv:"12", note:"+48 附加閃電傷害、+10 基礎閃電技能傷害", icon:"Topaz_spr_0", },
  { g:"寶石", name:"無暇黃寶石",         en:"Flawless_Topaz",               price:"", lv:"15", note:"+128 附加閃電傷害、+13 基礎閃電技能傷害", icon:"Flawless_Topaz_spr_0", },
  { g:"寶石", name:"完美黃寶石",         en:"Perfect_Topaz",                price:"", lv:"24", note:"+256 附加閃電傷害、+16 基礎閃電技能傷害", icon:"Perfect_Topaz_spr_0", },
  { g:"寶石", name:"嶄新黃寶石",         en:"Pristine_Topaz",               price:"", lv:"38", note:"+512 附加閃電傷害、+20 基礎閃電技能傷害", icon:"Pristine_Topaz_spr_0", },
  { g:"寶石", name:"碎裂紫水晶",         en:"Chipped_Amethyst",             price:"", lv:"1", note:"+8 附加奧術傷害、+4 基礎奧術技能傷害", icon:"Chipped_Amethyst_spr_0", },
  { g:"寶石", name:"瑕疵紫水晶",         en:"Flawed_Amethyst",              price:"", lv:"5", note:"+24 附加奧術傷害、+7 基礎奧術技能傷害", icon:"Flawed_Amethyst_spr_0", },
  { g:"寶石", name:"紫水晶",             en:"Amethyst",                     price:"", lv:"12", note:"+48 附加奧術傷害、+10 基礎奧術技能傷害", icon:"Amethyst_spr_0", },
  { g:"寶石", name:"無暇紫水晶",         en:"Flawless_Amethyst",            price:"", lv:"15", note:"+128 附加奧術傷害、+13 基礎奧術技能傷害", icon:"Flawless_Amethyst_spr_0", },
  { g:"寶石", name:"完美紫水晶",         en:"Perfect_Amethyst",             price:"", lv:"24", note:"+256 附加奧術傷害、+16 基礎奧術技能傷害", icon:"Perfect_Amethyst_spr_0", },
  { g:"寶石", name:"嶄新紫水晶",         en:"Pristine_Amethyst",            price:"", lv:"38", note:"+512 附加奧術傷害、+20 基礎奧術技能傷害", icon:"Pristine_Amethyst_spr_0", },
  { g:"寶石", name:"碎裂鑽石",           en:"Chipped_Diamond",              price:"", lv:"1", note:"+4 附加物理傷害", icon:"Chipped_Diamond_spr_0", },
  { g:"寶石", name:"瑕疵鑽石",           en:"Flawed_Diamond",               price:"", lv:"5", note:"+7 附加物理傷害", icon:"Flawed_Diamond_spr_0", },
  { g:"寶石", name:"鑽石",               en:"Diamond",                      price:"", lv:"12", note:"+10 附加物理傷害", icon:"Diamond_spr_0", },
  { g:"寶石", name:"無暇鑽石",           en:"Flawless_Diamond",             price:"", lv:"15", note:"+13 附加物理傷害", icon:"Flawless_Diamond_spr_0", },
  { g:"寶石", name:"完美鑽石",           en:"Perfect_Diamond",              price:"", lv:"24", note:"+16 附加物理傷害", icon:"Perfect_Diamond_spr_0", },
  { g:"寶石", name:"嶄新鑽石",           en:"Pristine_Diamond",             price:"", lv:"38", note:"+20 附加物理傷害", icon:"Pristine_Diamond_spr_0", },
  { g:"寶石", name:"碎裂頭骨",           en:"Chipped_Skull",                price:"", lv:"1", note:"+2% 擊中偷取生命", icon:"Chipped_Skull_spr_0", },
  { g:"寶石", name:"瑕疵頭骨",           en:"Flawed_Skull",                 price:"", lv:"5", note:"+4% 擊中偷取生命", icon:"Flawed_Skull_spr_0", },
  { g:"寶石", name:"頭骨",               en:"Skull",                        price:"", lv:"12", note:"+6% 擊中偷取生命", icon:"Skull_spr_0", },
  { g:"寶石", name:"無暇頭骨",           en:"Flawless_Skull",               price:"", lv:"15", note:"+8% 擊中偷取生命、+4% 生命回復", icon:"Flawless_Skull_spr_0", },
  { g:"寶石", name:"完美頭骨",           en:"Perfect_Skull",                price:"", lv:"24", note:"+10% 擊中偷取生命、+8% 生命回復", icon:"Perfect_Skull_spr_0", },
  { g:"寶石", name:"嶄新頭骨",           en:"Pristine_Skull",               price:"", lv:"38", note:"+12% 擊中偷取生命、+12% 生命回復", icon:"Pristine_Skull_spr_0", },

  /* ═══ 靈魂寶石與寶球 ═══ */
  { g:"靈魂寶石與寶球", name:"古拉格靈魂寶石",     en:"Gurag's Soulgem",              price:"", lv:"90", note:"+10 體力、+20% 生命回復、+40 傷害反彈", icon:"Boss_Gemstone_Gurag_spr_0", },
  { g:"靈魂寶石與寶球", name:"死神靈魂寶石",       en:"Death's Soulgem",              price:"", lv:"90", note:"+10 能量、+35% 魔力、+6 每秒魔力回復", icon:"Boss_Gemstone_Reaper_spr_0", },
  { g:"靈魂寶石與寶球", name:"阿努比斯靈魂寶石",   en:"Anubis' Soulgem",              price:"", lv:"90", note:"+10 力量、+10% 攻擊傷害、+5% 攻擊速度", icon:"Boss_Gemstone_Anubis_spr_0", },
  { g:"靈魂寶石與寶球", name:"達米安靈魂寶石",     en:"Damien's Soulgem",             price:"", lv:"90", note:"+5% 毒素傷害、+10% 毒素抗性、−5% 敵人毒素抗性", icon:"Damien_spr_0", },
  { g:"靈魂寶石與寶球", name:"卡普國王靈魂寶石",   en:"Karp King's Soulgem",          price:"", lv:"90", note:"+5% 閃電傷害、+10% 閃電抗性、−5% 敵人閃電抗性", icon:"Boss_Gemstone_Karp_spr_0", },
  { g:"靈魂寶石與寶球", name:"撒旦靈魂寶石",       en:"Satan's Soulgem",              price:"", lv:"90", note:"+5% 火焰傷害、+10% 火焰抗性、−5% 敵人火焰抗性", icon:"Boss_Gemstone_Satan_spr_0", },
  { g:"靈魂寶石與寶球", name:"梅維烏斯靈魂寶石",   en:"Mevius' Soulgem",              price:"", lv:"90", note:"+5% 奧術傷害、+10% 奧術抗性、−5% 敵人奧術抗性", icon:"Mevius_spr_0", },
  { g:"靈魂寶石與寶球", name:"奧丁靈魂寶石",       en:"Odin's Soulgem",               price:"", lv:"90", note:"+5% 冰霜傷害、+10% 冰霜抗性、−5% 敵人冰霜抗性", icon:"Boss_Gemstone_Odin_spr_0", },
  { g:"靈魂寶石與寶球", name:"克蘇魯的靈魂寶石",   en:"Cthulhu's Soulgem",            price:"", lv:"90", note:"+8% 所有元素抗性、+5 無視所有抗性", },
  { g:"靈魂寶石與寶球", name:"天使寶石",           en:"Angelic Gem",                  price:"", lv:"100", note:"+1 所有技能", icon:"Gem_Angelic_spr_0", },
  { g:"靈魂寶石與寶球", name:"混亂寶石",           en:"Chaos Gem",                    price:"", lv:"100", note:"+10% 法術技能傷害、+10 智力", icon:"Gem_Chaos_spr_0", },
  { g:"靈魂寶石與寶球", name:"元素寶石",           en:"Elemental Gem",                price:"", lv:"100", note:"+10 全屬性", icon:"Gem_Elemental_spr_0", },
  { g:"靈魂寶石與寶球", name:"月亮寶石",           en:"Moonstone Gem",                price:"", lv:"100", note:"+7% 攻擊速度、+7 力量、+7 敏捷", icon:"Gem_Moonstone_spr_0", },
  { g:"靈魂寶石與寶球", name:"化身寶石",           en:"Gem of Incarnation",           price:"", lv:"100", note:"遊戲檔沒有說明文字", },
  { g:"靈魂寶石與寶球", name:"哥布林石",           en:"Goblin",                       price:"", lv:"100", note:"+3 戰利品數量增加", icon:"Orb_of_Loot_Goblin_spr_0", },
  { g:"靈魂寶石與寶球", name:"符文熔爐石",         en:"Runeforge",                    price:"", lv:"100", note:"+7 符文掉落機率提高", icon:"Orb_of_Runeforge_spr_0", },
  { g:"靈魂寶石與寶球", name:"狗頭人石",           en:"Kobold",                       price:"", lv:"100", note:"+10 擊殺怪物獲得的金錢增加", icon:"Orb_of_Kobold_spr_0", },
  { g:"靈魂寶石與寶球", name:"英雄石",             en:"Heroism",                      price:"", lv:"100", note:"+4 英雄物品掉落機率增加", icon:"Orb_of_Heroism_spr_0", },
  { g:"靈魂寶石與寶球", name:"天使石",             en:"Angel",                        price:"", lv:"100", note:"+4 天使物品掉落機率增加", icon:"Orb_of_Angel_spr_0", },
  { g:"靈魂寶石與寶球", name:"迅捷石",             en:"Swiftness",                    price:"", lv:"100", note:"+15% 移動速度增加", icon:"Orb_of_Swiftness_spr_0", },
  { g:"靈魂寶石與寶球", name:"敏捷石",             en:"Agility",                      price:"", lv:"100", note:"+15% 攻擊速度增加", icon:"Orb_of_Agility_spr_0", },
  { g:"靈魂寶石與寶球", name:"魔導石",             en:"Magister",                     price:"", lv:"100", note:"+15% 施法速度增加", icon:"Orb_of_Magister_spr_0", },
  { g:"靈魂寶石與寶球", name:"野蠻石",             en:"Brute",                        price:"", lv:"100", note:"+20% 攻擊傷害增加", icon:"Orb_of_Brute_spr_0", },
  { g:"靈魂寶石與寶球", name:"智慧石",             en:"Wisdom",                       price:"", lv:"100", note:"+20 魔法技能傷害增加", icon:"Orb_of_Wisdom_spr_0", },
  { g:"靈魂寶石與寶球", name:"遺物石",             en:"Relic",                        price:"", lv:"100", note:"+3 擊殺遠古怪物時機率掉落遺物", icon:"Orb_of_Relic_spr_0", },
  { g:"靈魂寶石與寶球", name:"寶藏石",             en:"Treasure",                     price:"", lv:"100", note:"+1 擊殺遠古怪物時機率召喚寶藏哥布林", icon:"Orb_of_Treasure_spr_0", },
  { g:"靈魂寶石與寶球", name:"米達斯石",           en:"Midas",                        price:"", lv:"100", note:"+50% 物品稀有度增加", icon:"Orb_of_Midas_spr_0", },
  { g:"靈魂寶石與寶球", name:"角鬥士石",           en:"Gladiator",                    price:"", lv:"100", note:"+3% 經驗值獲得增加", icon:"Orb_of_Gladiator_spr_0", },
  { g:"靈魂寶石與寶球", name:"大地母親石",         en:"Earth",                        price:"", lv:"100", note:"+150 所有回復提高", icon:"Orb_of_Earth_Mother_spr_0", },
  { g:"靈魂寶石與寶球", name:"厄運石",             en:"Doom",                         price:"", lv:"100", note:"+1 怪物機率以軍團階級重生", icon:"Orb_of_Doom_spr_0", },
  { g:"靈魂寶石與寶球", name:"致命石",             en:"Fatality",                     price:"", lv:"100", note:"+150 暴擊傷害提高", icon:"Orb_of_Fatality_spr_0", },
  { g:"靈魂寶石與寶球", name:"遠古石",             en:"Ancient",                      price:"", lv:"100", note:"+5 機率生成古代怪物群", icon:"Orb_of_Ancient_spr_0", },

  /* ═══ 塔羅牌 ═══ */
  { g:"塔羅牌", name:"愚人",               en:"The Fool",                     price:"", },
  { g:"塔羅牌", name:"魔術師",             en:"The Magician",                 price:"", },
  { g:"塔羅牌", name:"女祭司",             en:"The High Priestess",           price:"", },
  { g:"塔羅牌", name:"女皇",               en:"The Empress",                  price:"", },
  { g:"塔羅牌", name:"皇帝",               en:"The Emperor",                  price:"", },
  { g:"塔羅牌", name:"教皇",               en:"The Hierophant",               price:"", },
  { g:"塔羅牌", name:"戀人",               en:"The Lovers",                   price:"", },
  { g:"塔羅牌", name:"戰車",               en:"The Chariot",                  price:"", },
  { g:"塔羅牌", name:"力量",               en:"Strength",                     price:"", },
  { g:"塔羅牌", name:"隱士",               en:"The Hermit",                   price:"", },
  { g:"塔羅牌", name:"命運之輪",           en:"The Wheel of Fortune",         price:"", },
  { g:"塔羅牌", name:"正義",               en:"Justice",                      price:"", },
  { g:"塔羅牌", name:"倒吊人",             en:"The Hanged Man",               price:"", },
  { g:"塔羅牌", name:"死神",               en:"Death",                        price:"", },
  { g:"塔羅牌", name:"節制",               en:"Temperance",                   price:"", },
  { g:"塔羅牌", name:"惡魔",               en:"The Devil",                    price:"", },
  { g:"塔羅牌", name:"高塔",               en:"The Tower",                    price:"", },
  { g:"塔羅牌", name:"星星",               en:"The Star",                     price:"", },
  { g:"塔羅牌", name:"月亮",               en:"The Moon",                     price:"", },
  { g:"塔羅牌", name:"太陽",               en:"The Sun",                      price:"", },
  { g:"塔羅牌", name:"審判",               en:"Judgement",                    price:"", },
  { g:"塔羅牌", name:"世界",               en:"The World",                    price:"", },
  { g:"塔羅牌", name:"神聖太陽",           en:"The Divine Sun",               price:"", },
  { g:"塔羅牌", name:"神聖月亮",           en:"The Divine Moon",              price:"", },
  { g:"塔羅牌", name:"神聖之堆",           en:"The Divine Pile",              price:"", },
  { g:"塔羅牌", name:"神聖失敗者",         en:"The Divine Failior",           price:"", },
  { g:"塔羅牌", name:"塔羅牌",             en:"Tarot Deck",                   price:"", },

  /* ═══ 碎片與王材料 ═══ */
  { g:"碎片與王材料", name:"次元碎片",           en:"Dimensional Shard",            price:"", note:"40 個開暗影領域傳送門 → 死亡陰影", icon:"Dimensional_Shard", },
  { g:"碎片與王材料", name:"戰鬥碎片",           en:"Battle Fragment",              price:"", note:"50 個開永恆戰場傳送門 → 李宋", icon:"Battle_Fragment", },
  { g:"碎片與王材料", name:"鬥獸場碎片",         en:"Colosseum Fragment",           price:"", note:"混沌塔 10 層掉，50 個 → 拉庫爾王", },
  { g:"碎片與王材料", name:"彩虹鑰匙碎片",       en:"Bifröst Fragment",             price:"", note:"合成彩虹鑰匙", },
  { g:"碎片與王材料", name:"古拉格的靈魂",       en:"Gurag's Soul",                 price:"", note:"古拉格掉 3.7%", icon:"Gurags_Soul", },
  { g:"碎片與王材料", name:"死亡印記",           en:"Death's Sigil",                price:"", note:"死神掉 3.7%", icon:"Deaths_Sigil", },
  { g:"碎片與王材料", name:"阿努比斯的生命之符", en:"Anubis' Ankh",                 price:"", note:"阿努比斯掉 3.7%", icon:"Anubis_Ankh", },
  { g:"碎片與王材料", name:"達米安之眼",         en:"Damien's Eye",                 price:"", note:"達米安掉 3.7%", icon:"Damiens_Eye", },
  { g:"碎片與王材料", name:"卡普王的肚臍",       en:"Karp King's Bellybutton",      price:"", note:"卡普國王掉 3.7%", icon:"Karp_Kings_Bellybutton", },
  { g:"碎片與王材料", name:"撒旦之角",           en:"Satan's Horn",                 price:"", note:"撒旦掉 3.7%", icon:"Satans_Horn", },
  { g:"碎片與王材料", name:"痛苦之魂",           en:"Soul of Anguish",              price:"", note:"墮落的達米安掉，地獄5 35%／煉獄 40%", icon:"Soul_of_Anguish", },
  { g:"碎片與王材料", name:"絕望之魂",           en:"Soul of Despair",              price:"", note:"死亡陰影掉，地獄5 35%／煉獄 40%", icon:"Soul_of_Despair", },
  { g:"碎片與王材料", name:"腐蝕之魂",           en:"Soul of Corruption",           price:"", note:"李宋掉，地獄5 35%／煉獄 40%", },
  { g:"碎片與王材料", name:"仇恨之魂",           en:"Soul of Hatred",               price:"", note:"三魂各 3 個合成 → 墮落天使加百列", icon:"Soul_of_Hatred", },
  { g:"碎片與王材料", name:"拉之捲軸",           en:"Scroll of Ra",                 price:"", note:"永恆死亡護符要 50 張", },
  { g:"碎片與王材料", name:"伊諾亞碎片",         en:"Fragment of Inoya",            price:"", note:"煉獄 1-4 阿爾伯特指揮官", },
  { g:"碎片與王材料", name:"苔原碎片",           en:"Fragment of Tundra",           price:"", note:"煉獄 2-5 大巫師安特羅", },
  { g:"碎片與王材料", name:"莫斯阿拉辛碎片",     en:"Fragment of Mos'Arathim",      price:"", note:"煉獄 3-2 赫爾格羅姆酋長", },
  { g:"碎片與王材料", name:"夢魘碎片",           en:"Fragment of Nightmare",        price:"", note:"煉獄 4-5 金塊", },
  { g:"碎片與王材料", name:"高津碎片",           en:"Fragment of Kaojin",           price:"", note:"煉獄 5-3 腐爛鯛魚", },
  { g:"碎片與王材料", name:"黎明碎片",           en:"Fragment of Dawn",             price:"", note:"煉獄 6-1 邪教領袖", },
  { g:"碎片與王材料", name:"時間碎片",           en:"Fragment of Time",             price:"", note:"煉獄 7-4 痛苦重現", },
  { g:"碎片與王材料", name:"存在印記",           en:"Signet of Existence",          price:"", note:"七章碎片各 1 合成 → 破碎領域", },
  { g:"碎片與王材料", name:"古錢幣",             en:"Ancient Coin",                 price:"", },
  { g:"碎片與王材料", name:"黃金代幣",           en:"Gold Token",                   price:"", },
  { g:"碎片與王材料", name:"娜迦鱗片",           en:"Naga Scale",                   price:"", },
  { g:"碎片與王材料", name:"神之精華",           en:"Essence of Gods",              price:"", },
  { g:"碎片與王材料", name:"布拉格礦碎片",       en:"Braggite Shard",               price:"", },

  /* ═══ 鑰匙 ═══ */
  { g:"鑰匙", name:"鑰匙",               en:"Basic Key",                    price:"", note:"開普通寶箱", },
  { g:"鑰匙", name:"水晶鑰匙",           en:"Crystal Key",                  price:"", note:"開水晶寶箱", },
  { g:"鑰匙", name:"雲鑰匙",             en:"Cloud Key",                    price:"", note:"區域 1-0", },
  { g:"鑰匙", name:"恐怖之鑰",           en:"Key of Terror",                price:"", note:"六隻章節王材料合成 → 陷落的伊諾亞", icon:"Key_of_Terror", },
  { g:"鑰匙", name:"紅寶石鑰匙",         en:"Ruby Key",                     price:"", note:"進紅寶石花園 → 恩德瑞西亞", icon:"Ruby_Key", },
  { g:"鑰匙", name:"天使鑰匙",           en:"Angelic Key",                  price:"", note:"魔術師×30 可合", icon:"Angelic_Key", },
  { g:"鑰匙", name:"瓦爾哈拉之鑰",       en:"Key to Valhalla",              price:"", },
  { g:"鑰匙", name:"彩虹鑰匙",           en:"Bifröst Key",                  price:"", note:"開彩虹橋，通往各 Uber BOSS", icon:"Bifröst_Key", },
  { g:"鑰匙", name:"神秘的鑰匙",         en:"Mysterious Key",               price:"", note:"區域 4-0", icon:"Mysterious_Key", },
  { g:"鑰匙", name:"庫拉坎之鑰",         en:"Curacan Key",                  price:"", note:"開庫拉坎之穴 3-4", icon:"Curacan_Key", },
  { g:"鑰匙", name:"永恆死亡護符",       en:"Ankh of Eternal Death",        price:"", note:"拉之捲軸×50＋天使鑰匙＋魔法符印×2", icon:"Warp_Key", },
  { g:"鑰匙", name:"混沌鑰匙",           en:"Chaos Key",                    price:"", },
  { g:"鑰匙", name:"煉獄恐懼之鑰",       en:"Key of Infernal Terror",       price:"", note:"煉獄版陷落的伊諾亞", },
  { g:"鑰匙", name:"煉獄永恆死亡護符",   en:"Ankh of Infernal Death",       price:"", note:"煉獄版阿蒙拉之墓", },
  { g:"鑰匙", name:"利維坦石板",         en:"Tablet of Leviathan",          price:"", note:"極北之島 → 北境洞穴", },
  { g:"鑰匙", name:"無敵艦隊石板",       en:"Tablet of Armada",             price:"", note:"沉船海灣 → 骷髏洞窟", },
  { g:"鑰匙", name:"寄生蟲石板",         en:"Tablet of Parasite",           price:"", note:"折磨之礁 → 心臟密室", },

  /* ═══ 地下城鑰匙 ═══ */
  { g:"地下城鑰匙", name:"臭奶酪",             en:"",                             price:"", note:"鼠洞（1-1）", icon:"Smelly_Cheese", },
  { g:"地下城鑰匙", name:"地窖鑰匙",           en:"",                             price:"", note:"南瓜地窖（1-3）", icon:"Cellar_Key", },
  { g:"地下城鑰匙", name:"塔樓鑰匙",           en:"",                             price:"", note:"黑塔（1-4）", icon:"Tower_Key", },
  { g:"地下城鑰匙", name:"結霜鑰匙",           en:"",                             price:"", note:"冰凍地窖（2-1）", icon:"Frosted_Key", },
  { g:"地下城鑰匙", name:"銅鑰匙",             en:"",                             price:"", note:"舊銅礦井（4-1）", icon:"Copper_Key", },
  { g:"地下城鑰匙", name:"神秘鑰匙",           en:"",                             price:"", note:"被遺忘的城市（3-3）", icon:"Mystic_Key", },
  { g:"地下城鑰匙", name:"生鏽的鑰匙",         en:"",                             price:"", note:"廢棄礦井（4-2）", icon:"Rusted_Key", },
  { g:"地下城鑰匙", name:"鏟子鑰匙",           en:"",                             price:"", note:"沙洞（3-2）", icon:"Shovel_Key", },
  { g:"地下城鑰匙", name:"古代鑰匙",           en:"",                             price:"", note:"古城（2-5）", icon:"Ancient_Key", },
  { g:"地下城鑰匙", name:"墓穴鑰匙",           en:"",                             price:"", note:"卡夫拉克斯墓（3-5）", icon:"Tomb_Key", },
  { g:"地下城鑰匙", name:"魔鬼的鑰匙",         en:"",                             price:"", note:"魔鬼之穴（4-5）", icon:"Devils_Key", },
  { g:"地下城鑰匙", name:"鎬鑰匙",             en:"",                             price:"", note:"富士火山口（5-1）", icon:"Pickaxe_Key", },
  { g:"地下城鑰匙", name:"戰鬥鑰匙",           en:"",                             price:"", note:"高津寺（5-3）", icon:"Battle_Key", },
  { g:"地下城鑰匙", name:"花園鑰匙",           en:"",                             price:"", note:"地下花園（5-2）", icon:"Garden_Key", },
  { g:"地下城鑰匙", name:"金鑰匙",             en:"",                             price:"", note:"寺廟暗門（5-5）", icon:"Golden_Key", },
  { g:"地下城鑰匙", name:"斧頭鑰匙",           en:"",                             price:"", note:"無標記墳墓（6-1）", icon:"Axe_Key", },
  { g:"地下城鑰匙", name:"勇氣鑰匙",           en:"",                             price:"", note:"格拉茲海姆大廳（8-1）", icon:"Valor_Key", },
  { g:"地下城鑰匙", name:"納迦鱗片鑰匙",       en:"",                             price:"", note:"娜迦神廟（8-2）", icon:"Naga_Scale_Key", },
  { g:"地下城鑰匙", name:"岩漿鑰匙",           en:"",                             price:"", note:"穆斯貝爾海姆（8-3）", icon:"Magma_Key", },
  { g:"地下城鑰匙", name:"地獄之火火炬",       en:"",                             price:"", note:"尼夫海姆（8-5）", icon:"Hellflame_Key", },
  { g:"地下城鑰匙", name:"扭曲鑰匙",           en:"",                             price:"", note:"扭曲地平線（7-2）", icon:"Warp_Key", },
  { g:"地下城鑰匙", name:"儲藏室鑰匙",         en:"",                             price:"", note:"武器儲藏室（6-4）", icon:"Storage_Key", },
  { g:"地下城鑰匙", name:"北極鑰匙",           en:"",                             price:"", note:"北境洞穴（9-4）", },
  { g:"地下城鑰匙", name:"寄生鑰匙",           en:"",                             price:"", note:"巨獸之腹（9-3）", },
  { g:"地下城鑰匙", name:"寶藏鑰匙",           en:"",                             price:"", note:"骷髏洞窟（9-2）", },
  { g:"地下城鑰匙", name:"蜂巢鑰匙",           en:"",                             price:"", note:"黃蜂巢穴（9-1）", },
  { g:"地下城鑰匙", name:"阿茲特克鑰匙",       en:"",                             price:"", note:"阿茲特克金字塔", },

  /* ═══ 特殊消耗品 ═══ */
  { g:"特殊消耗品", name:"賭徒代幣",           en:"Gambler's Token",              price:"", note:"賭博／重抽用", },
  { g:"特殊消耗品", name:"打孔代幣",           en:"Socketing Token",              price:"", note:"打孔用", },
  { g:"特殊消耗品", name:"古代謎題",           en:"Ancient Puzzle",               price:"", },
  { g:"特殊消耗品", name:"精華靈藥",           en:"Essence Elixir",               price:"", note:"喝了給化身精華", },
  { g:"特殊消耗品", name:"煉獄仇恨之魂",       en:"Soul of Infernal Hatred",      price:"", note:"開煉獄仇恨之環", },

];
