/* ============================================================
   英文 → 繁體中文 對照表

   過濾器比對的一律是英文（遊戲底層名稱），這個檔案負責翻成中文顯示。
   查不到的會直接顯示英文，不會亂猜。

   要新增就照格式往下加：  "English Name": "中文名",
   譯名請以你自己的客戶端為準——下面是我整理的，可能有錯。
   ============================================================ */

const TERMS = {

  /* ── 物品類別 Class ────────────────────────── */
  "Stackable Currency": "通貨",
  "Currency": "通貨",
  "Divination Cards": "命運卡",
  "Maps": "地圖",
  "Map Fragments": "地圖碎片",
  "Misc Map Items": "地圖物品",
  "Gems": "技能寶石",
  "Jewel": "珠寶",
  "Abyss Jewel": "深淵珠寶",
  "Body Armours": "胸甲",
  "Helmets": "頭盔",
  "Gloves": "手套",
  "Boots": "鞋子",
  "Shields": "盾牌",
  "Belts": "腰帶",
  "Rings": "戒指",
  "Amulets": "護身符",
  "Quivers": "箭袋",
  "Flasks": "藥劑",
  "Life Flasks": "生命藥劑",
  "Mana Flasks": "魔力藥劑",
  "Hybrid Flasks": "複合藥劑",
  "Tinctures": "酊劑",
  "Charms": "咒符",
  "Bows": "弓",
  "Wands": "法杖",
  "Staves": "長杖",
  "Warstaves": "戰杖",
  "Sceptres": "短杖",
  "Claws": "爪",
  "Daggers": "匕首",
  "Rune Daggers": "符文匕首",
  "One Hand Swords": "單手劍",
  "Two Hand Swords": "雙手劍",
  "One Hand Axes": "單手斧",
  "Two Hand Axes": "雙手斧",
  "One Hand Maces": "單手錘",
  "Two Hand Maces": "雙手錘",
  "Thrusting One Hand Swords": "細劍",
  "Fishing Rods": "釣竿",
  "Contract": "契約書",
  "Blueprint": "藍圖",
  "Heist Target": "賞金目標",
  "Heist Gear": "賞金裝備",
  "Heist Tool": "賞金工具",
  "Heist Cloak": "賞金披風",
  "Heist Brooch": "賞金胸針",
  "Trinket": "飾品",
  "Expedition Logbook": "遠征日誌",
  "Breachstone": "裂痕石",
  "Vault Keys": "聖物庫鑰匙",
  "Sanctum Research": "聖殿探查",
  "Corpses": "屍體",
  "Relic": "遺物",
  "Quest Items": "任務物品",
  "Atlas Upgrade Item": "虛空石",
  "Incursion Item": "穿越物品",
  "Leaguestones": "聯盟石",
  "Sentinel Drone": "靈能護衛",
  "Pieces": "傳奇碎片",
  "Idol": "雕像",
  "Chart": "海圖",
  "Gold": "金幣",

  /* ── 高階通貨 ──────────────────────────────── */
  "Mirror of Kalandra": "卡蘭德的魔鏡",
  "Mirror Shard": "魔鏡碎片",
  "Divine Orb": "神聖石",
  "Exalted Orb": "崇高石",
  "Exalted Shard": "崇高石碎片",
  "Awakener's Orb": "覺醒者石",
  "Orb of Dominance": "支配之玉",
  "Eternal Orb": "永恆寶珠",
  "Fracturing Orb": "破裂石",
  "Fracturing Shard": "破裂碎片",
  "Hinekora's Lock": "希奈可拉之鎖",
  "Reflecting Mist": "映像迷霧",
  "Tempering Orb": "回火石",
  "Tailoring Orb": "裁縫石",
  "Sacred Orb": "神聖之石",
  "Ancient Orb": "遠古寶珠",
  "Orb of Annulment": "剝離石",
  "Annulment Shard": "剝離碎片",
  "Orb of Unmaking": "粉碎石",
  "Veiled Chaos Orb": "隱匿混沌石",
  "Veiled Exalted Orb": "隱匿崇高石",
  "Crescent Splinter": "新月裂片",
  "Facetor's Lens": "費斯特的透鏡",
  "Orb of Conflict": "衝突寶珠",
  "Valdo's Puzzle Box": "瓦爾多的謎之匣",

  /* ── 一般通貨 ──────────────────────────────── */
  "Chaos Orb": "混沌石",
  "Chaos Shard": "混沌碎片",
  "Regal Orb": "富豪石",
  "Regal Shard": "富豪碎片",
  "Orb of Alchemy": "點金石",
  "Alchemy Shard": "點金碎片",
  "Orb of Alteration": "改造石",
  "Alteration Shard": "改造碎片",
  "Orb of Transmutation": "蛻變石",
  "Transmutation Shard": "蛻變碎片",
  "Orb of Augmentation": "增幅石",
  "Orb of Chance": "機會石",
  "Orb of Fusing": "鏈結石",
  "Jeweller's Orb": "工匠石",
  "Chromatic Orb": "幻色石",
  "Blessed Orb": "祝福石",
  "Orb of Scouring": "重鑄石",
  "Orb of Regret": "後悔石",
  "Orb of Binding": "綑綁石",
  "Orb of Horizons": "地平線寶珠",
  "Harbinger's Orb": "先驅者寶珠",
  "Vaal Orb": "瓦爾寶珠",
  "Gemcutter's Prism": "寶石匠的稜鏡",
  "Glassblower's Bauble": "玻璃匠的小珠",
  "Cartographer's Chisel": "製圖師的鑿子",
  "Armourer's Scrap": "護甲片",
  "Blacksmith's Whetstone": "磨刀石",
  "Scroll of Wisdom": "知識卷軸",
  "Scroll Fragment": "卷軸碎片",
  "Portal Scroll": "傳送卷軸",
  "Stacked Deck": "命運卡組",
  "Silver Coin": "銀幣",
  "Perandus Coin": "普蘭德金幣",
  "Rogue's Marker": "賞金印記",
  "Instilling Orb": "灌輸寶珠",
  "Enkindling Orb": "點燃寶珠",
  "Ritual Vessel": "驅靈法器",
  "Divine Vessel": "禁靈之瓶",
  "Albino Rhoa Feather": "白化羅亞羽毛",
  "Orb of Unravelling": "拆解石",
  "Scrying Orb": "靈視寶珠",
  "Orb of Remembrance": "回想石",
  "Orb of Intention": "意志石",
  "Imprint": "拓印",
  "Imprinted Bestiary Orb": "拓印的封魔之玉",

  /* ── 汙穢 / 異界通貨 ───────────────────────── */
  "Tainted Chaos Orb": "汙穢混沌石",
  "Tainted Exalted Orb": "汙穢崇高石",
  "Tainted Mythic Orb": "汙穢神秘石",
  "Tainted Divine Teardrop": "汙穢神聖之淚",
  "Tainted Blessing": "汙穢祝福石",
  "Tainted Catalyst": "汙穢催化劑",
  "Tainted Oil": "汙穢聖油",
  "Eldritch Chaos Orb": "異界混沌石",
  "Eldritch Exalted Orb": "異界崇高石",
  "Eldritch Orb of Annulment": "異界剝離石",
  "Eldritch Ember": "異界餘燼",
  "Eldritch Ichor": "異界靈液",

  /* ── 精華與化石 ────────────────────────────── */
  "Remnant of Corruption": "腐化精華",
  "Fractured Fossil": "分裂化石",
  "Faceted Fossil": "稜面化石",
  "Hollow Fossil": "鏤空化石",
  "Glyphic Fossil": "雕刻化石",
  "Bloodstained Fossil": "濺血化石",
  "Gilded Fossil": "鑲金化石",
  "Tangled Fossil": "糾纏化石",
  "Bound Fossil": "綁縛化石",
  "Deft Fossil": "暴擊化石",
  "Fundamental Fossil": "屬性化石",
  "Serrated Fossil": "狼牙化石",
  "Sanctified Fossil": "聖潔化石",
  "Prismatic Fossil": "五彩化石",
  "Pristine Fossil": "原始化石",
  "Dense Fossil": "緻密化石",
  "Aberrant Fossil": "畸變化石",
  "Metallic Fossil": "金屬化石",
  "Frigid Fossil": "冰冽化石",
  "Scorched Fossil": "熾炎化石",
  "Jagged Fossil": "鋸齒化石",
  "Corroded Fossil": "腐蝕化石",
  "Aetheric Fossil": "乙太化石",
  "Lucent Fossil": "透光化石",
  "Shuddering Fossil": "震顫化石",

  /* ── 聖油 ─────────────────────────────────── */
  "Golden Oil": "金色聖油",
  "Silver Oil": "白銀聖油",
  "Opalescent Oil": "乳白聖油",
  "Black Oil": "漆黑聖油",
  "Crimson Oil": "緋紅聖油",
  "Violet Oil": "紫色聖油",
  "Azure Oil": "天藍聖油",
  "Teal Oil": "水藍聖油",
  "Verdant Oil": "翠綠聖油",
  "Amber Oil": "琥珀聖油",
  "Sepia Oil": "墨色聖油",
  "Clear Oil": "清澈聖油",
  "Prismatic Oil": "彩虹聖油",
  "Reflective Oil": "反射聖油",
  "Indigo Oil": "靛藍聖油",

  /* ── 碎片與裂片 ────────────────────────────── */
  "Splinter of Chayula": "恰幽拉裂片",
  "Splinter of Uul-Netol": "烏爾尼特裂片",
  "Splinter of Xoph": "佐斯裂片",
  "Splinter of Tul": "托爾裂片",
  "Splinter of Esh": "艾許裂片",
  "Blessing of Chayula": "恰幽拉的祝福",
  "Blessing of Uul-Netol": "烏爾尼特的祝福",
  "Blessing of Xoph": "佐斯的祝福",
  "Blessing of Tul": "托爾的祝福",
  "Blessing of Esh": "艾許的祝福",
  "Simulacrum Splinter": "擬像裂片",
  "Ritual Splinter": "驅靈裂片",
  "Timeless Karui Splinter": "永恆卡魯裂片",
  "Timeless Vaal Splinter": "永恆瓦爾裂片",
  "Timeless Eternal Empire Splinter": "永恆帝國裂片",
  "Timeless Templar Splinter": "永恆聖堂裂片",
  "Timeless Maraketh Splinter": "永恆瑪拉克斯裂片",
  "Sacrifice at Midnight": "午夜的獻祭",
  "Sacrifice at Dawn": "黎明的獻祭",
  "Sacrifice at Noon": "正午的獻祭",
  "Sacrifice at Dusk": "黃昏的獻祭",
  "Mortal Hope": "凡人的希望",
  "Mortal Ignorance": "凡人的無知",
  "Mortal Rage": "凡人的憤怒",
  "Mortal Grief": "凡人的哀傷",
  "Fragment of the Phoenix": "鳳凰碎片",
  "Fragment of the Minotaur": "牛頭人碎片",
  "Fragment of the Chimera": "奇美拉碎片",
  "Fragment of the Hydra": "九頭蛇碎片",
  "Fragment of Terror": "恐懼斷片",
  "Fragment of Emptiness": "空虛斷片",
  "Fragment of Shape": "雕塑斷片",
  "Fragment of Knowledge": "智慧斷片",
  "Fragment of Enslavement": "奴役斷片",
  "Fragment of Eradication": "根除斷片",
  "Fragment of Constriction": "干擾斷片",
  "Fragment of Purification": "淨化斷片",
  "Chronicle of Atzoatl": "阿茲亞特神廟",
  "Inscribed Ultimatum": "貪婪戰書",
  "Simulacrum": "夢魘擬像",
  "The Maven's Writ": "馬文的敕令",
  "Blood-filled Vessel": "浸血法器",

  /* ── 其他常見 ──────────────────────────────── */
  "Ceremonial Voidstone": "儀式虛空石",
  "Decayed Voidstone": "腐朽虛空石",
  "Eldritch Voidstone": "異界虛空石",
  "Originator Voidstone": "起源虛空石",
  "Thief's Trinket": "盜賊飾品",
  "Enshrouding Crystal": "霧影水晶",
  "Maraketh Enshrouding Crystal": "瑪拉克斯霧影水晶",
  "Flesh of Xesht": "薛斯的血肉",

};
